version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo:/data/db

  task-manager:
    image: task-manager:latest
    container_name: task-manager
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-container:27017/mydatabase

volumes:
  mongo:

networks:
  my-network:
    driver: bridge
