swagger: "2.0"
info:
  version: "1.0.0"
  title: "Task API"
  description: "API for managing tasks"
basePath: "/tasks"
tags:
  - name: "tasks"
    description: "Operations related to tasks"
schemes:
  - "http"
paths:
  /:
    get:
      tags:
        - "tasks"
      summary: "Get all tasks"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
    post:
      tags:
        - "tasks"
      summary: "Create a new task"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Task object"
          required: true
          schema:
            $ref: "#/definitions/Task"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
  /{id}:
    get:
      tags:
        - "tasks"
      summary: "Get task by ID"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the task to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
    delete:
      tags:
        - "tasks"
      summary: "Delete task by ID"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the task to delete"
          required: true
          type: "string"
      responses:
        204:
          description: "No Content"
    put:
      tags:
        - "tasks"
      summary: "Update task by ID"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the task to update"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Updated task object"
          required: true
          schema:
            $ref: "#/definitions/Task"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
definitions:
  Task:
    type: "object"
    properties:
      id:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
      dueDate:
        type: "string"
        format: "date"
      tags:
        type: "array"
        items:
          type: "string"
      status:
        $ref: "#/definitions/TaskStatus"
    required:
      - "title"
  TaskStatus:
    type: "string"
    enum:
      - "PENDING"
      - "ONGOING"
      - "COMPLETED"
